import React, { useState, useRef, useEffect, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Download, FileText, TableProperties, Loader2, ChevronDown, CheckCircle2 } from 'lucide-react';
import jsPDF from 'jspdf';
import Papa from 'papaparse';

/* ═══════════════════════════════════════════════════════════
   HELPERS
   ═══════════════════════════════════════════════════════════ */

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

/**
 * Formats the metrics + shapValues objects into a flat array
 * of rows suitable for CSV / PDF table rendering.
 */
const buildRows = (metrics = {}, shapValues = {}) => {
  const metricRows = Object.entries(metrics).map(([key, value]) => ({
    section: 'Fairness Metric',
    name: key.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase()),
    value: typeof value === 'number' ? `${Math.round(value * 100)}%` : String(value),
    status: value >= 0.7 ? 'Fair' : value >= 0.5 ? 'Warning' : 'Biased',
  }));

  const shapRows = Object.entries(shapValues).map(([key, value]) => ({
    section: 'SHAP Feature Impact',
    name: key.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase()),
    value: typeof value === 'number' ? (value > 0 ? `+${value.toFixed(3)}` : value.toFixed(3)) : String(value),
    status: value >= 0 ? 'Positive' : 'Negative',
  }));

  return [...metricRows, ...shapRows];
};

/* ── CSV Export ── */
const exportCSV = (rows, filename = 'fairlens-report.csv') => {
  const csv = Papa.unparse(rows, { header: true });
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  link.click();
  URL.revokeObjectURL(url);
};

/* ── PDF Export ── */
const exportPDF = (rows, filename = 'fairlens-report.pdf') => {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 40;
  let y = margin;

  /* ── Header bar ── */
  doc.setFillColor(107, 47, 191);
  doc.rect(0, 0, pageW, 54, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('FairLens', margin, 34);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('AI Fairness Audit Report', margin + 80, 34);

  const dateStr = new Date().toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  });
  doc.text(dateStr, pageW - margin, 34, { align: 'right' });

  y = 80;

  /* ── Section grouping ── */
  const sections = [...new Set(rows.map((r) => r.section))];

  sections.forEach((section) => {
    const sectionRows = rows.filter((r) => r.section === section);

    /* Section title */
    doc.setFillColor(27, 28, 29);
    doc.roundedRect(margin, y - 4, pageW - margin * 2, 22, 4, 4, 'F');
    doc.setTextColor(214, 186, 255);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text(section, margin + 8, y + 11);
    y += 30;

    /* Column headers */
    const colX = [margin, margin + 200, margin + 340, margin + 430];
    const headers = ['Metric / Feature', 'Value', 'Status', ''];
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(136, 135, 128);
    headers.forEach((h, i) => doc.text(h, colX[i], y));
    y += 6;
    doc.setDrawColor(60, 60, 65);
    doc.setLineWidth(0.5);
    doc.line(margin, y, pageW - margin, y);
    y += 12;

    /* Rows */
    doc.setFont('helvetica', 'normal');
    sectionRows.forEach((row, idx) => {
      if (y > doc.internal.pageSize.getHeight() - 60) {
        doc.addPage();
        y = margin + 20;
      }

      /* Alternating row bg */
      if (idx % 2 === 0) {
        doc.setFillColor(31, 32, 33);
        doc.rect(margin, y - 9, pageW - margin * 2, 16, 'F');
      }

      /* Status colour */
      const statusColor =
        row.status === 'Fair' || row.status === 'Positive' ? [29, 158, 117] :
        row.status === 'Warning' ? [239, 159, 39] :
        [226, 75, 74];

      doc.setFontSize(9);
      doc.setTextColor(227, 226, 227);
      doc.text(row.name, colX[0], y);

      doc.setFont('helvetica', 'bold');
      doc.text(row.value, colX[1], y);
      doc.setFont('helvetica', 'normal');

      doc.setTextColor(...statusColor);
      doc.text(row.status, colX[2], y);
      doc.setTextColor(227, 226, 227);

      y += 18;
    });

    y += 14;
  });

  /* ── Footer ── */
  doc.setFontSize(8);
  doc.setTextColor(136, 135, 128);
  doc.text(
    `Generated by FairLens • ${dateStr}`,
    pageW / 2,
    doc.internal.pageSize.getHeight() - 20,
    { align: 'center' }
  );

  doc.save(filename);
};

/* ═══════════════════════════════════════════════════════════
   DROPDOWN OPTION  (accessible, keyboard-navigable)
   ═══════════════════════════════════════════════════════════ */
const DropdownOption = ({ icon: Icon, label, description, onClick, index }) => (
  <motion.button
    role="menuitem"
    tabIndex={0}
    onClick={onClick}
    initial={{ opacity: 0, x: -8 }}
    animate={{ opacity: 1, x: 0 }}
    transition={{ duration: 0.18, delay: index * 0.06 }}
    whileHover={{ x: 3 }}
    className="w-full flex items-center gap-3 px-4 py-3 rounded-xl text-left
               transition-all duration-200 cursor-pointer group
               hover:bg-white/[0.06] focus:outline-none focus:bg-white/[0.06]
               active:bg-white/[0.09]"
    style={{ border: 'none', background: 'transparent' }}
  >
    <div className="p-2 rounded-lg bg-[#6b2fbf]/10 border border-[#6b2fbf]/20
                    group-hover:bg-[#6b2fbf]/20 group-hover:border-[#6b2fbf]/40
                    transition-all duration-200 flex-shrink-0">
      <Icon size={14} className="text-[#d6baff]" />
    </div>
    <div className="min-w-0">
      <p className="text-[13px] font-semibold text-[#e3e2e3] leading-tight">{label}</p>
      <p className="text-[11px] text-[#888780] mt-0.5 leading-tight">{description}</p>
    </div>
  </motion.button>
);

/* ═══════════════════════════════════════════════════════════
   EXPORT REPORT — Main Component
   ═══════════════════════════════════════════════════════════ */
/**
 * Props:
 *   metrics    { [key: string]: number }  — fairness metric scores
 *   shapValues { [key: string]: number }  — SHAP feature values
 *   label      string                     — optional button label override
 */
const ExportReport = ({ metrics = {}, shapValues = {}, label = 'Download Report' }) => {
  const [open, setOpen] = useState(false);
  const [loadingType, setLoadingType] = useState(null); // 'csv' | 'pdf' | null
  const [successType, setSuccessType] = useState(null);
  const menuRef = useRef(null);
  const triggerRef = useRef(null);

  /* ── Close on outside click or Escape ── */
  useEffect(() => {
    const handleKeyDown = (e) => {
      if (e.key === 'Escape') setOpen(false);
    };
    const handleClick = (e) => {
      if (menuRef.current && !menuRef.current.contains(e.target)) {
        setOpen(false);
      }
    };
    document.addEventListener('keydown', handleKeyDown);
    document.addEventListener('mousedown', handleClick);
    return () => {
      document.removeEventListener('keydown', handleKeyDown);
      document.removeEventListener('mousedown', handleClick);
    };
  }, []);

  /* ── Focus first item when menu opens ── */
  useEffect(() => {
    if (open) {
      const firstItem = menuRef.current?.querySelector('[role="menuitem"]');
      firstItem?.focus();
    }
  }, [open]);

  /* ── Arrow key navigation within menu ── */
  const handleMenuKeyDown = useCallback((e) => {
    const items = [...(menuRef.current?.querySelectorAll('[role="menuitem"]') ?? [])];
    const current = document.activeElement;
    const idx = items.indexOf(current);
    if (e.key === 'ArrowDown') {
      e.preventDefault();
      items[(idx + 1) % items.length]?.focus();
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      items[(idx - 1 + items.length) % items.length]?.focus();
    }
  }, []);

  const handleExport = useCallback(async (type) => {
    setOpen(false);
    setLoadingType(type);
    const rows = buildRows(metrics, shapValues);
    await sleep(800); // simulate generation time for UX feedback

    try {
      if (type === 'csv') {
        exportCSV(rows);
      } else {
        exportPDF(rows);
      }
      setSuccessType(type);
      await sleep(2000);
      setSuccessType(null);
    } catch (err) {
      console.error('Export failed:', err);
    } finally {
      setLoadingType(null);
    }
  }, [metrics, shapValues]);

  const isLoading = loadingType !== null;
  const isSuccess = successType !== null;

  return (
    <div ref={menuRef} className="relative inline-block" onKeyDown={handleMenuKeyDown}>
      {/* ── Trigger button ── */}
      <motion.button
        ref={triggerRef}
        id="export-report-btn"
        aria-haspopup="menu"
        aria-expanded={open}
        aria-label="Export audit report"
        onClick={() => !isLoading && setOpen((v) => !v)}
        disabled={isLoading}
        whileHover={!isLoading ? { scale: 1.02, y: -1 } : {}}
        whileTap={!isLoading ? { scale: 0.98 } : {}}
        className="premium-btn relative inline-flex items-center gap-2.5
                   px-5 py-2.5 rounded-xl text-white font-semibold text-[13px]
                   cursor-pointer focus:outline-none focus-visible:ring-2
                   focus-visible:ring-[#6b2fbf]/60 focus-visible:ring-offset-2
                   focus-visible:ring-offset-[#121315]
                   disabled:cursor-not-allowed disabled:opacity-60
                   transition-all duration-200 select-none"
        style={{ minWidth: 160 }}
      >
        {/* Button content */}
        <AnimatePresence mode="wait" initial={false}>
          {isLoading ? (
            <motion.span
              key="loading"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="flex items-center gap-2"
            >
              <Loader2 size={15} className="animate-spin flex-shrink-0" />
              <span>Generating {loadingType?.toUpperCase()}…</span>
            </motion.span>
          ) : isSuccess ? (
            <motion.span
              key="success"
              initial={{ opacity: 0, scale: 0.85 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0 }}
              className="flex items-center gap-2"
            >
              <CheckCircle2 size={15} className="text-emerald-300 flex-shrink-0" />
              <span>Downloaded!</span>
            </motion.span>
          ) : (
            <motion.span
              key="idle"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="flex items-center gap-2"
            >
              <Download size={15} className="flex-shrink-0" />
              <span>{label}</span>
              <motion.span
                animate={{ rotate: open ? 180 : 0 }}
                transition={{ duration: 0.2 }}
              >
                <ChevronDown size={13} />
              </motion.span>
            </motion.span>
          )}
        </AnimatePresence>

        {/* Shimmer overlay while loading */}
        {isLoading && (
          <span
            className="absolute inset-0 rounded-xl shimmer-bg opacity-40 pointer-events-none"
          />
        )}
      </motion.button>

      {/* ── Dropdown menu ── */}
      <AnimatePresence>
        {open && (
          <motion.div
            role="menu"
            aria-label="Export options"
            initial={{ opacity: 0, scale: 0.95, y: -6 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: -6 }}
            transition={{ duration: 0.18, ease: [0.4, 0, 0.2, 1] }}
            className="glass-panel absolute right-0 top-[calc(100%+8px)] z-50
                       w-64 rounded-2xl p-2 shadow-[0_24px_64px_-12px_rgba(0,0,0,0.7)]"
            style={{
              border: '1px solid rgba(107, 47, 191, 0.18)',
              boxShadow: '0 24px 64px -12px rgba(0,0,0,0.7), 0 0 0 1px rgba(107,47,191,0.12), inset 0 1px 0 rgba(255,255,255,0.04)',
            }}
          >
            {/* Menu header */}
            <div className="px-4 pt-2 pb-3 border-b border-white/[0.05] mb-1">
              <p className="text-[10px] uppercase tracking-[0.14em] font-semibold text-[#888780]">
                Export Format
              </p>
            </div>

            <DropdownOption
              index={0}
              icon={TableProperties}
              label="Export as CSV"
              description="Spreadsheet-ready data table"
              onClick={() => handleExport('csv')}
            />
            <DropdownOption
              index={1}
              icon={FileText}
              label="Export as PDF"
              description="Formatted audit report"
              onClick={() => handleExport('pdf')}
            />

            {/* Footer */}
            <div className="px-4 pt-3 pb-2 border-t border-white/[0.05] mt-1">
              <p className="text-[10px] text-[#888780]/60 leading-relaxed">
                Includes all fairness metrics &amp; SHAP values
              </p>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
};

export default ExportReport;
